refactor: changed type of styles
geta-org/sex-adapt-mobile pull request #117
Opened 2023-04-12 19:12 UTC by LeticiaMalato

pro Freitas me julgar

2023-04-12 23:51 UTC, ryanolivrdev requested changes
Ajustar os comentários feitos e me marcar novamente aqui para revisar

2023-04-12 23:51 UTC, ryanolivrdev commented on src/components/Swiper/index.tsx
> +}
Dar um espaço
```suggestion
}

```

2023-04-12 23:51 UTC, ryanolivrdev commented on src/components/Swiper/index.tsx
> +export function Swiper({ alt, height, width, ...rest }: SwiperProps) {
```suggestion
export function SwiperPhotos({ height, width, ...rest }: ISwiperProps) {
```

2023-04-12 23:51 UTC, ryanolivrdev commented on src/components/Swiper/index.tsx
> +            uri: item.imageUrl
Tu podes olhar bem aqui de estabelecimento
https://sex-adapt.westus3.cloudapp.azure.com/docs#/Establishment%20Routes

2023-04-12 23:51 UTC, ryanolivrdev commented on src/screens/App/MotelDetails/index.tsx
> +      <ImageContainer>
Eu acho que tu podes remover isso e ajustar o tamanho pelo componente de Swiper. Testar isso e claro.

2023-04-12 23:51 UTC, ryanolivrdev commented on src/components/Swiper/index.tsx
> +const DATA = [
Remover esse Array, e passar para tela de MotelDetails.

2023-04-17 13:52 UTC, olucasfreitas commented on src/components/Swiper/index.tsx
> +      keyExtractor={(item) => item.id}
Não precisa pois a gente vai receber essas fotos do back, assim tá ótimo por enquanto

2023-04-17 13:54 UTC, olucasfreitas requested changes
No video, na parte de baixo do swiper, tem a barra de rolagem ainda aparecendo, remover essa barra

80794a8457a5edfe1c17d8dacd14ca478abf7f3d

2023-04-17 14:50 UTC, ryanolivrdev commented on src/components/Swiper/index.tsx
> +      keyExtractor={(item) => item.id}
O backend não retorna id nas fotos, por isso meu question. 

![image](https://user-images.githubusercontent.com/66662333/232522931-658d7d60-3ea2-423a-a21a-aa943338e24b.png)

2023-04-17 14:51 UTC, olucasfreitas commented on src/components/Swiper/index.tsx
> +      keyExtractor={(item) => item.id}
cria uma issue pra modificar isso lá

2023-04-17 17:49 UTC, LeticiaMalato commented on src/components/Swiper/index.tsx
> +          height={200}
59ba54637df2eb5537222d2d7bbcaccfcc6bf519

2023-04-17 17:49 UTC, LeticiaMalato commented on src/components/Swiper/index.tsx
> +          height={200}
59ba54637df2eb5537222d2d7bbcaccfcc6bf519

2023-04-17 17:50 UTC, LeticiaMalato commented on src/components/Swiper/index.tsx
> +export interface SwiperProps {
b602514a3fd89a80c7b8baad5c698745c9bf2d32

2023-04-17 17:50 UTC, LeticiaMalato commented on src/components/Swiper/index.tsx
> +  alt?: string;
b602514a3fd89a80c7b8baad5c698745c9bf2d32

2023-04-17 17:50 UTC, LeticiaMalato commented on src/components/Swiper/index.tsx
> +export function Swiper({ alt, height, width, ...rest }: SwiperProps) {
b602514a3fd89a80c7b8baad5c698745c9bf2d32

2023-04-18 00:40 UTC, olucasfreitas approved these changes

2023-04-18 00:40 UTC, merged