refactor: changed some questions and some zod's names
geta-org/sex-adapt-mobile pull request #124
Opened 2023-05-21 20:25 UTC by LeticiaMalato

##Overview
Was changed the suggestions question to match up the schema words from backend.

#How was this ?
![WhatsApp Image 2023-05-21 at 17 23 45](https://github.com/geta-org/sex-adapt-mobile/assets/102633079/3d010102-32ef-44d9-8662-707fa44503dc)
![WhatsApp Image 2023-05-21 at 17 23 46](https://github.com/geta-org/sex-adapt-mobile/assets/102633079/70fbbfde-3ba9-4123-8fb1-a2c11bb43dcc)

2023-05-24 19:28 UTC, ryanolivrdev requested changes

2023-05-24 19:28 UTC, ryanolivrdev commented on src/hooks/useEstablishments.tsx
> +export function createSuggestion(formData: {
aplicar aqui tambem a interface

2023-05-24 19:28 UTC, ryanolivrdev commented on src/hooks/useEstablishments.tsx
> +  createSuggestion: (
aplicar aqui tambem a interface

2023-05-25 15:47 UTC, olucasfreitas commented on src/hooks/useEstablishments.tsx
> +
remover espaço

2023-05-25 15:48 UTC, olucasfreitas commented on src/hooks/useEstablishments.tsx
> +import { ISuggestionEntity } from '@entities/suggestion/suggestion.interface';
Isso aqui não precisa existir

2023-05-25 15:50 UTC, olucasfreitas commented on src/screens/App/Suggestion/index.tsx
> +        title: 'Erro ao enviar as informações',
te falei pra colocar o error.message aqui

2023-05-26 02:29 UTC, LeticiaMalato commented on src/hooks/useEstablishments.tsx
> +
47389a57c2d9323805a6a3e112dbe5ff614981e4

2023-05-26 02:30 UTC, LeticiaMalato commented on src/hooks/useEstablishments.tsx
> +import { ISuggestionEntity } from '@entities/suggestion/suggestion.interface';
051ec6eae47bd1975bbe4eb34b2139a9ac316207

2023-05-26 02:31 UTC, LeticiaMalato commented on src/screens/App/Suggestion/index.tsx
> +        title: 'Erro ao enviar as informações',
dd62d9d4fb4fc169c42d962eb25139683d821ff9

2023-05-26 02:32 UTC, LeticiaMalato commented on src/screens/App/Suggestion/index.tsx
> +  function createSuggestion(formData: {
e99ffd637ade60238e650aac717db6c438c83b2d

2023-05-30 00:33 UTC, olucasfreitas approved these changes

2023-05-30 00:33 UTC, merged