Feat/pagehome
geta-org/sex-adapt-mobile pull request #13
Opened 2022-10-12 18:34 UTC by ryanolivrdev

## Overview
Creation of the home and motel details screens and fix some bugs in the svg, besides fixing the application routes to work with 2 types of navigation

## How to test it
Run `expo start` and navigate the home and click on a card.

## Results
![HomePage](https://user-images.githubusercontent.com/66662333/195420950-ba6e73f3-17e5-4fb9-a8a9-228219f2aaba.jpeg)

![Details](https://user-images.githubusercontent.com/66662333/195421057-edcedf3a-8e58-45fd-9f58-0a95f0b4b454.jpeg)

## Notes
there is a delay bug in the TabBar when switching from one screen to another

2022-10-13 21:50 UTC, olucasfreitas requested changes

2022-10-13 21:50 UTC, olucasfreitas commented on src/components/Button/ButtonRound/index.tsx
> +  text?: string;
vapo

2022-10-13 21:50 UTC, olucasfreitas commented on src/components/Button/ButtonRound/index.tsx
> +  label: string;
vapo

2022-10-13 21:50 UTC, olucasfreitas commented on src/components/Button/ButtonRound/index.tsx
> +  subtitle: string;
vapo

2022-10-13 21:50 UTC, olucasfreitas commented on src/components/Card/CardAccessibility/index.tsx
> +  elevator?: boolean;
conserta

2022-10-13 21:50 UTC, olucasfreitas commented on src/components/Card/CardAccessibility/index.tsx
> +    <CardAccessibilityConteiner>
CONTEINER  é ruim

2022-10-13 21:50 UTC, olucasfreitas commented on src/components/Card/CardAccessibilityText/index.tsx
> +  ramp?: boolean;
conserta

2022-10-13 21:50 UTC, olucasfreitas commented on src/components/PriceRating/index.tsx
> +        style={{
passar pra styled components

2022-10-13 21:50 UTC, olucasfreitas commented on src/routes/app.routes.tsx
> +          // tabBarStyle: { display: 'none' },
vapo

2022-10-14 18:06 UTC, ryanolivrdev commented
## Overview of the settings
Correct the things discussed and organize the styles of each screen

![Home](https://user-images.githubusercontent.com/66662333/195912452-195580a9-8b5f-4eac-9dce-a77b14442cfb.jpeg)
![MotelDetails](https://user-images.githubusercontent.com/66662333/195912481-13be2e81-090f-4ba8-ab1b-0f3a036d6ca9.jpeg)

2022-10-17 22:55 UTC, olucasfreitas approved these changes

2022-10-17 22:55 UTC, merged