feat/ProjectSettings
geta-org/sex-adapt-mobile pull request #2
Opened 2022-09-17 03:33 UTC by ryanolivrdev

## Overview #1 
To start the project development, it was necessary to configure dependencies, folders, routes, default application theme, husky for "cute" commits, splash screen and scripts for the json package.

## How to test it
Run `expo start` and navigate the routes.

## Results

@FabioNeves00 thanks for the help setting up husky and commitlint :)

2022-09-19 13:25 UTC, olucasfreitas commented on package.json
> +    "postinstall": "npx husky install .husky && chmod ug+x .husky/* && chmod ug+x .git/hooks/* && npm install eslint --location=global"
muda para "post-install"

2022-09-19 13:29 UTC, olucasfreitas requested changes

2022-09-19 13:29 UTC, olucasfreitas commented on src/contexts/useAuth.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
comenta a função inteira com o //TODO em cima

2022-09-21 02:16 UTC, ryanolivrdev commented
@olucasfreitas finalized review adjustments

2022-09-21 20:04 UTC, olucasfreitas approved these changes

2022-09-21 20:05 UTC, merged