Feat/login
geta-org/sex-adapt-mobile pull request #3
Opened 2022-09-22 14:18 UTC by LeticiaMalato

2022-10-05 01:05 UTC, olucasfreitas commented on src/screens/Auth/SignIn/index.tsx
> +  InputPassword,
Não são necessários 2 inputs, criar apenas um

2022-10-05 01:11 UTC, olucasfreitas requested changes
Prestar mais atenção no código upado, usar eslint e prettier extensions no vscode para formatação do código, commits estão uma piada, usar padrão que foi requisitado, e commitar com mais frequência ao invés de apenas mandar tudo de uma vez só

2022-10-05 01:11 UTC, olucasfreitas commented on src/screens/Auth/SignIn/index.tsx
> +  InputPassword,
Não são necessários 2 inputs, criar apenas um

2022-10-05 01:11 UTC, olucasfreitas commented on src/screens/Auth/SignIn/index.tsx
> +  TextSingUp,
Corrigir inglês para SignUpText

2022-10-05 01:11 UTC, olucasfreitas commented on src/screens/Auth/SignIn/index.tsx
> +  ButtonSingUp,
Corrigir inglês para SignUpButton

2022-10-05 01:11 UTC, olucasfreitas commented on src/screens/Auth/SignIn/index.tsx
> +      <StatusBar style="light" />
Remover config da status bar daqui, colocar no app.tsx

2022-10-05 01:11 UTC, olucasfreitas commented on src/screens/Auth/SignIn/index.tsx
> +      <LoginWrapper>
Mudar para FormWrapper

2022-10-05 01:11 UTC, olucasfreitas commented on src/screens/Auth/SignIn/styles.ts
> +  background-color: #cc3333;
Ajeitar alinhamento

2022-10-05 01:11 UTC, olucasfreitas commented on src/screens/Auth/SignIn/styles.ts
> +flex: 1;
Não faz sentindo usar flex e display

2022-10-05 01:11 UTC, olucasfreitas commented on src/screens/Auth/SignIn/styles.ts
> +export const TextSingUp =styled.Text`color: #fff;
ajeitar formatação

2022-10-05 01:11 UTC, olucasfreitas commented on src/screens/Auth/SignIn/styles.ts
> +//border-bottom-width: 1px;
remover comentário

2022-10-05 01:11 UTC, olucasfreitas commented on src/screens/Auth/SignIn/styles.ts
> +//height: 6%;
remover comentário

2022-10-14 19:00 UTC, ryanolivrdev commented on src/screens/Auth/SignUp/index.tsx
> +        <CaretLeft size={32}  />
ajustar o alinhamento dessa pagina, usar o prettier e uma boa. (Clicar botão direito e ir em formatar documento)

2022-10-17 23:48 UTC, olucasfreitas approved these changes

2022-10-17 23:48 UTC, merged