Feat/ settings menu
geta-org/sex-adapt-mobile pull request #52
Opened 2023-01-10 17:58 UTC by LeticiaMalato

created the setting menu, componentized the icons

2023-01-11 21:17 UTC, olucasfreitas requested changes

2023-01-11 21:17 UTC, olucasfreitas commented on src/components/Button/ButtonSupport/styles.ts
> +  /* font-size: ${({ theme }) => theme.font_size.sm}; */
código comentado não passará

2023-01-11 21:17 UTC, olucasfreitas commented on src/screens/App/Evaluation/index.tsx
> +const styles = StyleSheet.create({
eu entendi o motivo do uso do StyleSheet, mas acho melhor usar ele só no elemento especifico em que queres colocar a sombra

2023-01-31 19:51 UTC, ryanolivrdev commented
MERGE CONFLICTS RESOLVER

2023-01-31 19:53 UTC, olucasfreitas approved these changes

2023-01-31 19:54 UTC, merged