Feature/create button component
geta-org/sex-adapt-mobile pull request #87
Opened 2023-02-13 01:03 UTC by olucasfreitas

Created button component with native base

2023-02-13 21:27 UTC, ryanolivrdev requested changes

2023-02-13 21:27 UTC, ryanolivrdev commented on src/screens/Auth/Accessibility/index.tsx
> +  const [loading, setLoading] = React.useState(false);
Não está sendo usado em nenhum lugar essa variável.

2023-02-13 21:27 UTC, ryanolivrdev commented on src/screens/Auth/ChangePassword/index.tsx
> +import React from 'react';
colocar import na primeira linha

2023-02-13 21:27 UTC, ryanolivrdev commented on src/screens/Auth/RecoverPassword/index.tsx
> +import React from 'react';
colocar import na primeira linha

2023-02-13 21:27 UTC, ryanolivrdev commented on src/screens/App/MotelDetails/index.tsx
> +import React from 'react';
colocar import na primeira linha

2023-02-13 21:27 UTC, ryanolivrdev commented on src/screens/Auth/Accessibility/index.tsx
> +  const [buttonLoading, setButtonLoading] = React.useState(false);
Em todos os outros lugares da aplicação está sendo chamado apenas de loading, não seria interessante manter um padrão nessas variáveis ( mudar tudo pra buttonLoading ou trocar essa pra loading )

2023-02-13 21:27 UTC, ryanolivrdev commented on src/screens/Auth/SignIn/index.tsx
> +import React from 'react';
import na primeira linha

2023-02-13 21:27 UTC, ryanolivrdev commented on src/screens/Auth/SignUp/index.tsx
> +import React from 'react';
import na primeira linha

2023-02-13 21:27 UTC, ryanolivrdev commented on src/components/Button/RoundedButton/index.tsx
> +interface ButtonBaseProps extends TouchableOpacityProps {
nesse caso, não seria melhor extender as props do próprio native base?

2023-02-13 21:34 UTC, olucasfreitas commented on src/components/Button/RoundedButton/index.tsx
> +interface ButtonBaseProps extends TouchableOpacityProps {
não achei como fazer isso, pesquisa e me manda os docs

2023-02-14 01:56 UTC, olucasfreitas commented on src/screens/Auth/Accessibility/index.tsx
> +  const [loading, setLoading] = React.useState(false);
![image](https://user-images.githubusercontent.com/54646059/218618695-6a77cbcf-2199-489f-8710-9c82b0f2edfb.png)
tá sendo usada bem aqui, quando consertarmos o componente removemos

2023-02-14 02:11 UTC, ryanolivrdev approved these changes

2023-02-14 02:17 UTC, merged