Feature | Integration establishments with api
geta-org/sex-adapt-mobile pull request #91
Opened 2023-02-14 18:43 UTC by ryanolivrdev

## Overview
- the establishments were integrated with the api, in addition to some improvements in the code

## How was it?
![WhatsApp Image 2023-02-14 at 15 32 05](https://user-images.githubusercontent.com/66662333/218828487-5e01effa-3cdc-4fcd-868e-891297d5be4c.jpeg)

![WhatsApp Image 2023-02-14 at 15 32 06](https://user-images.githubusercontent.com/66662333/218828454-94df88e1-dab5-49ad-a99b-30b32a0ee220.jpeg)

2023-02-14 23:02 UTC, olucasfreitas requested changes
linka com as issues corretas

2023-02-14 23:02 UTC, olucasfreitas commented on src/screens/App/Map/index.tsx
> +                {/* // REMOVER ESSA IMPLEMENTACAO ??? */}
não entendi o comentário

2023-02-14 23:02 UTC, olucasfreitas commented on src/screens/App/MotelDetails/index.tsx
> +  const address = formattedFullAddress(establishment.address);
formatedAdress

2023-02-14 23:02 UTC, olucasfreitas commented on src/screens/App/MotelDetails/index.tsx
> +              startingValue={establishment.stars}
rating

2023-02-14 23:08 UTC, ryanolivrdev commented
> linka com as issues corretas

essa branch envolve tanto a #79, quanto a #89.

2023-02-14 23:10 UTC, ryanolivrdev commented on src/screens/App/MotelDetails/index.tsx
> +              startingValue={establishment.stars}
No backend, estou recebendo esse json com start.

2023-02-14 23:11 UTC, ryanolivrdev commented on src/screens/App/Map/index.tsx
> +                {/* // REMOVER ESSA IMPLEMENTACAO ??? */}
Como não vai ter o uso das rotas com a api do google, fica o questionamento de remover essa funcionalidade

2023-02-14 23:13 UTC, olucasfreitas commented on src/screens/App/Map/index.tsx
> +                {/* // REMOVER ESSA IMPLEMENTACAO ??? */}
pode remover

2023-02-14 23:18 UTC, ryanolivrdev commented on src/components/Map/CalloutView/index.tsx
> +  const distanceBetweenEstablishment = getDistanceBetweenEstablishment({
Isso já e uma Util, mas preciso passar essas informacoes. 

Pode ser encontrada em helpers/getDistanceBetweenEstablishment

2023-02-14 23:24 UTC, ryanolivrdev commented on src/components/Map/MotelMarker/index.tsx
> +interface IUserLocation {
podes me dar um exemplo de como ficaria a pasta de interfaces com essa e a IAddress?

2023-02-14 23:40 UTC, ryanolivrdev commented on src/hooks/useEstablishments.tsx
> +  const getAll = useCallback(async () => {
Basicamente, o useCallback memoiza a função e evita que ela seja redeclarada sempre que componentes filhos que utilizam essa função sejam renderizado. E como eu não estou passando nada no array de dependência ele nunca vai ficar redeclarando.

2023-02-15 00:25 UTC, ryanolivrdev commented on src/components/Card/CardMotel/index.tsx
> +              startingValue={establishment.stars}
Estou recebendo no json como starts, tenho que mudar?

2023-02-15 13:34 UTC, olucasfreitas commented on src/screens/App/MotelDetails/index.tsx
> +              startingValue={establishment.stars}
blz, vou pedir pra ele mudar, por enquanto deixa assim

2023-02-15 13:34 UTC, olucasfreitas commented on src/components/Card/CardMotel/index.tsx
> +    // eslint-disable-next-line prettier/prettier
ainda esperando remover

2023-02-15 13:35 UTC, olucasfreitas commented on src/components/Card/CardMotel/index.tsx
> +    (async () => {
remover linha comentada e mover função para função externa

2023-02-15 13:36 UTC, olucasfreitas commented on src/components/Map/CalloutView/index.tsx
> +  const distanceBetweenEstablishment = getDistanceBetweenEstablishment({
ok, só muda o nome então

2023-02-15 22:28 UTC, olucasfreitas commented on src/helpers/getDistanceBetweenEstablishment.ts
> +  const distanceBetweenMotel = (
```suggestion
  const distanceBetweenMotelAndUser = (
```

2023-02-16 22:10 UTC, olucasfreitas commented on src/helpers/getDistanceBetweenEstablishment.ts
> +  const distanceBetweenMotel = (
@ryanolivrdev esqueceu aqui ó

2023-02-28 01:51 UTC, merged